### ISSUE TITLE
<source> with a sub element leads to invalid JavaScript output

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/gulp-xliff-to-carbon-i18n#1]
I have a `trans-unit` that has its source marked as non-translatable:

```
<trans-unit resname="key">
  <source xml:lang="en">
     <mrk mtype="protected">non-translatable</mrk>
  </source>
</trans-unit>
```

This makes the gulp task produce a multi line entry, which is not valid JavaScript:

```
key: '
  non-translatable
',
```

The correct behavior would be to ignore the spaces before and after the `<mrk>`:
```
key: 'non-translatable'
```

Only workaround right now is to remove the spaces from the XLIFF file (which is an issue for auto-generated XLIFF files):
```
<trans-unit resname="key">
  <source xml:lang="en"><mrk mtype="protected">non-translatable</mrk></source>
</trans-unit>
```

**Comment by ankon** [comment]
Ok, so there is basically two issues ... 
1. These 'mrk' things: ignore them when producing the strings, they are just there for the translators.
2. <source> content is to be collapsed.

Will fix that in the XSL quickly, and then need to check the schema for more of those.

**Comment by ankon** [comment]
Note that the main issue here was the `xml:space` handling in the XLIFF itself, which fixed the problem of producing multiline JS strings as a side-effect. It is probably still possible to produce multiline strings now, if the XLIFF file actually says that. We can work out what to do at that point.
