### ISSUE TITLE
New lines disappeared 

### ISSUE THREAD

**Issue by kovacicmilan** [Collaborne/gulp-xliff-to-carbon-i18n#4]
I created in xliff file text that has new lines in it.

```
<trans-unit id="..._introduction" resname="..._introduction">
                    <source>For example consider following expences:
* the salaries
* ensurence
* advertising
* taxes</source>
                    <note from="developer">Introduces the ideas that user should consider</note>
```

 After that I used gulp to generate JS files. 

```
...introduction: 'For example consider following expences: * the salaries * ensurence * advertising * taxes',
```

However in JS files the newlines disappeared completely.

**Comment by ankon** [comment]
This is actually a side-effect/variant of #1: #1 is about removing the whitespace-only nodes around `<source>`, but the fix actually introduced the newline removing behavior we see here now.
